### ISSUE TITLE
utils.less??

### ISSUE THREAD

**Issue by rjpalermo1** [leolassence/meteor-1.4-blaze-boilerplate#1]
Hi, 

giving it a go based on your boiler plate.

Have a question, in app-not-found.less you have @import '../stylesheets/utils.less';

Do you mean to @import @import '../stylesheets/base.less'; ?

**Comment by leolassence** [comment]
Hi, yes think it's an issue

Can you fork and do a pull request to fix it ?

Cheers

2016-08-12 15:06 GMT+02:00 rjpalermo1 <notifications@github.com>:

**Comment by leolassence** [comment]
@rjpalermo1 it's have been fixed 👍
