### ISSUE TITLE
Error from npm run dev

### ISSUE THREAD

**Issue by gauravkeerthi** [leolassence/meteor-1.4-blaze-boilerplate#2]

**Comment by leolassence** [comment]
Hi,

Did you solved your issue ?

Best regards

2016-12-03 11:04 GMT+01:00 gauravkeerthi <notifications@github.com>:

**Comment by gauravkeerthi** [comment]
Yes. My installation was not complete for some reason so I reinstalled it.

**Comment by leolassence** [comment]
Nice ! le t me know if you have other questions or issues

2016-12-03 13:56 GMT+01:00 gauravkeerthi <notifications@github.com>:

> Yes. My installation was not complete for some reason so I reinstalled it.
>
